spring.application.name=credito.api

#Resilience
resilience4j.retry.instances.produtoCredito.max-attempts=3
resilience4j.retry.instances.produtoCredito.wait-duration=1s
resilience4j.retry.instances.produtoCredito.enable-exponential-backoff=true
resilience4j.retry.instances.produtoCredito.exponential-backoff-multiplier=2